#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generates Secrets.generated.swift from a .env file so ScreenScraper developer
# credentials never end up in the repository. The values are XOR-obfuscated —
# this is not security (a shipped binary can always be inspected), it only
# keeps them out of plain `strings` output.
#
# Usage: generate-secrets.sh <path/to/.env> <output.swift>

set -eu

ENV_FILE="${1:-.env}"
OUTPUT="${2:-Ursprung/Support/Secrets.generated.swift}"

DEV_ID=""
DEV_PASSWORD=""

if [ -f "$ENV_FILE" ]; then
    DEV_ID=$(grep -E '^SCREENSCRAPER_DEV_ID=' "$ENV_FILE" | head -n1 | cut -d= -f2- | tr -d '\r"' || true)
    DEV_PASSWORD=$(grep -E '^SCREENSCRAPER_DEV_PASSWORD=' "$ENV_FILE" | head -n1 | cut -d= -f2- | tr -d '\r"' || true)
fi

# Environment variables win (useful for CI).
DEV_ID="${SCREENSCRAPER_DEV_ID:-$DEV_ID}"
DEV_PASSWORD="${SCREENSCRAPER_DEV_PASSWORD:-$DEV_PASSWORD}"

encode() {
    # Prints the XOR-obfuscated bytes of $1 as a Swift array literal.
    printf '%s' "$1" | /usr/bin/python3 -c '
import sys
key = 0x5A
data = sys.stdin.buffer.read()
print("[" + ", ".join(str((b ^ ((key + i * 31) & 0xFF))) for i, b in enumerate(data)) + "]")
'
}

TMP="$(mktemp)"
cat > "$TMP" <<EOF
// Generated by Scripts/generate-secrets.sh — do not edit, do not commit.
nonisolated enum GeneratedSecrets {
    static let screenScraperDevID: [UInt8] = $(encode "$DEV_ID")
    static let screenScraperDevPassword: [UInt8] = $(encode "$DEV_PASSWORD")
}
EOF

# Only touch the file when the content changed, to avoid needless rebuilds.
if [ ! -f "$OUTPUT" ] || ! cmp -s "$TMP" "$OUTPUT"; then
    mkdir -p "$(dirname "$OUTPUT")"
    mv "$TMP" "$OUTPUT"
else
    rm -f "$TMP"
fi
